### ISSUE TITLE
Is easy rules capable of providing fact feedback while analyzing rules?

### ISSUE THREAD

**Issue by jjzazuet** [benas/easy-rules#17]
Hi. My apologies if the question is not specific enough. However, I think that when Drools evaluates a rule codebase with existing facts, whenever a rule is triggered, said rule could insert or retract facts from the working memory; thus triggering other rules.

Does `easyrules` have this capability? Thanks!

**Comment by benas** [comment]
Hi, Easy Rules is quite different from Drools. There are no concepts of facts and working memory. In Easy Rules, rules are triggered in sequence according to their natural order (which is priority by default). So if a rule adds or removes "a fact", the next rule could be designed to evaluate this fact and be triggered accordingly.

For example, in [this tutorial](http://www.easyrules.org/tutorials/rule-priority.html), the `AgeRule` adds a fact that Tom is not adult. The next rule, `AlcoholRule`, based on the fact that Tom is not adult, denies him from buying alcohol.

So concepts are quite different from drools, that's why I'm not sure we can say if easy rules has this capability or not. It depends on how rules are designed and how they are designed to be triggered.

I hope I answered your question :-)
