### ISSUE TITLE
Good job!

### ISSUE THREAD

**Issue by simosentissi** [benas/easy-rules#2]
just stumbled on this library, this is really good work!

**Comment by drem-darios** [comment]
Great library! I agree this is a nice simple and lightweight solution between drools and a custom predicate. I had to fork and remove the JMX support to use this library with Android though. The java.lang.management library depends on the JVM which Android doesn't use. Just thought I would mention this. Cheers!

**Comment by benas** [comment]
Hi @drem-darios 
Thank you, I'm glad you liked it :-)

I was not aware that the JMX API is not supported on Android and I understand why you had to fork Easy Rules. You have removed all the JMX related code from the engine but there still the `@MXBean` annotation on the `Rule` interface in [your fork](https://github.com/drem-darios/easy-rules/blob/master/easyrules-core/src/main/java/org/easyrules/api/Rule.java#L37). Is this ok with Android? There still a JMX import for this annotation. Does Android can run easy rules with this annotation present?

This is important because, if so, I have to redesign Easy Rules to make the JMX reconfiguration feature optional so that the core engine can be used in Java and Android. I have to provide a better design so that users should not fork the project and remove a feature, they should instead fork the project to add a feature maybe :-)

Regards
Mahmoud

PS: I just posted this message on [gitter](https://gitter.im/benas/easy-rules). I think it's a better place to continue this discussion.
