### ISSUE TITLE
Can't register multiple rules with the same priority to DefaultRulesEngine

### ISSUE THREAD

**Issue by beccagaspard** [benas/easy-rules#6]
I noticed that if you register multiple rules with the same priority to the DefaultRulesEngine, only the first rule will be added to the set and fired.  Looks like this is due to the behavior of TreeSet which uses compareTo for all element comparison.  Maybe DefaultRulesEngine should use ArrayList like AnnotatedRulesEngine so they have the same behavior?

    SimpleRule rule1 = new SimpleRule("rule 1", "description 1", 0);
    SimpleRule rule2 = new SimpleRule("rule 2", "description 2", 0);
    SimpleRule rule3 = new SimpleRule("rule 3", "description 3", 1);

    RulesEngine<Rule> engine = new DefaultRulesEngine();
    engine.registerRule(rule1);
    engine.registerRule(rule2);
    engine.registerRule(rule3);
    engine.fireRules();

    assertTrue(rule1.isExecuted());
    assertTrue(rule2.isExecuted()); //fails
    assertTrue(rule3.isExecuted());

Really like the library - great lightweight alternative to drools :)

**Comment by benas** [comment]
Hi Becca,

Thank you, I'm glad you like it :-)

In fact, it is impossible to register 2 rules with the same priority. Actually this is due to the implementation of `compareTo` method of `BasicRule` class which is incompatible with the `equalsTo` method. `compareTo` and `equalsTo` should be implemented in a consistent way (see javadoc of [TreeSet](http://docs.oracle.com/javase/7/docs/api/java/util/TreeSet.html) and [Comparator](http://docs.oracle.com/javase/7/docs/api/java/util/Comparator.html) ):

> The ordering imposed by a comparator c on a set of elements S is said to be consistent with equals if and only if c.compare(e1, e2)==0 has the same boolean value as e1.equals(e2) for every e1 and e2 in S.

This is not the case currently, in the `BasicRule` class:
- `equalTo` is based on the rule name
- `compareTo` is based on priority

And this is why when we try to insert 2 rules with different names but with the same priority, only one of them is inserted. 

Even worse, currently, we can create a rule without specifying a priority, in this case, the rule's priority will be assigned to a default value. This means that if we create 2 rules without specifying their priority, both of them will have the same default priority and *only* one of them will be registered!

```java
Set<SimpleRule> rules = new TreeSet<SimpleRule>();
SimpleRule rule1 = new SimpleRule("rule 1", "description 1");
SimpleRule rule2 = new SimpleRule("rule 2", "description 2");
rules.add(rule1);
rules.add(rule2);
assertEquals(2, rules.size()); // fails: expected = 2, actual = 1
```
This test currently fails! Hurry up, I'll fix that asap! :-)

Thank you for pointing out this issue! I'll fix it asap and keep you informed.

Best regards
Mahmoud

**Comment by benas** [comment]
Hi Becca,

I've fixed this issue in version 1.3.0-SNAPSHOT. `equals` and `compareTo` are now implemented in a consistent way. The test you provided is passing now (see [here](https://github.com/benas/easy-rules/blob/master/easyrules-core/src/test/java/org/easyrules/core/test/parameters/DefaultRulesEngineTest.java#L17)).

I've [uploaded](https://oss.sonatype.org/content/repositories/snapshots/org/easyrules/easyrules-core/) version 1.3.0-SNAPSHOT to maven central repository, could you please check if everything is ok for you and keep me informed?

Many thanks
Regards
Mahmoud

**Comment by beccagaspard** [comment]
Hi Mahmoud,

Just tried out the 1.3.0-SNAPSHOT version and it seems to be working fine for me.

Thanks for the quick fix! :)
-Becca

**Comment by benas** [comment]
Great!

Keep tuned for next release :-)

Cheers
Mahmoud
